### ISSUE TITLE
p5.js browser version

### ISSUE THREAD

**Issue by fmr1202** [Lartu/p5.clickable#10]
not sure if anyone else has this issue, but I can't get it to run on the browser version of p5. it gives me an error that Clickable() is not defined

**Comment by Agusnez** [comment]
Are you sure that you have the **_p5.clickable.js_** file in your environment and the corresponding `<script src="p5.clickable.js"></script>` tag pointing to the right file path? For me it's working just fine.

**Comment by Samathingamajig** [comment]
Make sure to either make a new file called p5.clickable.js and copy/paste the code in their or download this project and upload just that file. Also, if you put it in a lib [library] folder, you'd need to change the script tag to `<script src="./lib/p5.clickable.js"></script>`

And the most important thing is to have that script tag be below the `p5.min.js` script tag but above all of your personal code, especially `sketch.js`

**Comment by Lartu** [comment]
> And the most important thing is to have that script tag be below the p5.min.js script tag but above all of your personal code, especially sketch.js

This is quite important! I'll add it to the readme file. Thank you!

@fmr1202 has the issue been solved?

**Comment by Samathingamajig** [comment]
Any updates @fmr1202 ?
