### ISSUE TITLE
add support for image buttons

### ISSUE THREAD

**Issue by Lartu** [Lartu/p5.clickable#2]
what the title says

**Comment by Lartu** [comment]
i will take care of this

**Comment by Lartu** [comment]
great, thank you!

**Comment by Lartu** [comment]
😉

**Comment by Lartu** [comment]
It's been a year and you haven't fixed this yet.

**Comment by fredericpierron** [comment]
This is my dream!!

**Comment by Lartu** [comment]
I will try to add them as soon as possible! (or you can try to add them yourself and upload a pull request, it should be very easy to implement image buttons but I'm quite busy at the moment :S)

**Comment by zachkrall** [comment]
Hi @Lartu,
Is this something I could submit a PR for?
