### ISSUE TITLE
Upload to CDN / cdnjs.com

### ISSUE THREAD

**Issue by samyakbambole** [Lartu/p5.clickable#20]
This library should be uploaded to a CDN (Content Delivery Network) or cdnjs.com so that coders could use this library without downloading it.

**Comment by samyakbambole** [comment]
`<script src="cdn-url"></script>`

**Comment by zachkrall** [comment]
Hi @samyakbambole,
You can use the following script tag via jsdelivr
```
<script defer src="https://cdn.jsdelivr.net/gh/lartu/p5.clickable@1.2/library/p5.clickable.js"></script>
```
