### ISSUE TITLE
Release and Press Bug

### ISSUE THREAD

**Issue by bettywolfy** [Lartu/p5.clickable#26]
Found a bug in the button!
If you press a button and move the mouse off the button, it doesn't call the onReleased function.

```
this.reset_btn = new Clickable();
this.reset_btn.text = "CLICK!";
this.reset_btn.onPress = function() {
	this.text = "Move mouse out button!";
	this.color = "#000";
	this.textColor = "#fff";
}
this.reset_btn.onRelease = function() {
	this.text = "Fixed?";
        this.color = "#fff";
	this.textColor = "#000";
}
```

**Comment by ArztKlein** [comment]
That is intended behaviour so you can cancel an accidental click

**Comment by Samathingamajig** [comment]
This is how HTML buttons work, and buttons in most applications

**Comment by bettywolfy** [comment]
Não, esse comportamento não acontece no meu!
Não dá pra cancelar um evento click ;-;

**Comment by Samathingamajig** [comment]
As mentioned above, this is the intended behavior, meaning this is what is supposed to happen.
