### ISSUE TITLE
Link to another html file

### ISSUE THREAD

**Issue by andreeaparsley97** [Lartu/p5.clickable#9]
Hi! I was wondering how can I implement opening another window after pressing a button?

**Comment by Lartu** [comment]
Hi there! The process would be like this:

```javascript
//First create the clickable
myButton = new Clickable();    
//Then set an action for when it is pressed
myButton.onPress = function(){
  window.open('https://www.google.com');
}
```

You can also resize and move and customize the clickable, [check the docs](https://github.com/Lartu/p5.clickable#microscope-documentation) for information on how to do that. If you have any questions do not hesitate to ask! :smile:

**Comment by Lartu** [comment]
(You can also use `onRelease` instead of `onPress` for a more accurate button experience. Most buttons on normal GUIs activate when they are released, not when they are pressed.)

**Comment by Lartu** [comment]
I'm marking this as closed as I believe the question has been answered. Don't hesitate to open it again if it wasn't ;)
